# Generated by Django 4.2.1 on 2023-07-11 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
