# Generated by Django 4.2.1 on 2023-07-10 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
